// export const base_url = "https://gokap.onrender.com";
export const base_url = "http://localhost:8000"
export const signInApiPoint = "/api/user/login/";
export const signUpApiPoint = "/api/user/signup";
export const signInGoogleApiPoint = "/api/user/login/google/";
export const profileApi = "/api/user/profile/";
export const assignProjectApi = "";
export const getAllProjectApi = "";
export const projectUnAssignedApi = "/api/project/unassigned/"
